Updated cray-tftp-upload script to handle more than one ipxe pod (CSM1.5)

diff --git a/cms-tftp/cray-tftp-upload b/cms-tftp/cray-tftp-upload
--- a/cms-tftp/cray-tftp-upload
+++ b/cms-tftp/cray-tftp-upload
@@ -24,6 +24,10 @@
 
 UPLOAD_FILE=$1
 PVC_HOST=`kubectl get pods -n services -l app.kubernetes.io/instance=cms-ipxe -o custom-columns=NS:.metadata.name --no-headers`
+# if more then one host is returned, use the 1st one.
+if [ `echo $PVC_HOST | wc -w` -gt 1 ]; then
+  PVC_HOST=`echo $PVC_HOST | awk '{print $1}'`
+fi
 PVC_PATH="/shared_tftp"
 
 usage()
@@ -45,9 +49,10 @@ else
     echo "$UPLOAD_FILE is not a file. Exiting."
     exit 1
 fi
-if [ $? -ne 0 ]; then
-    echo "Failed to upload $UPLOAD_FILE - error code = $?"
-    exit $?
+retval=$?
+if [ $retval -ne 0 ]; then
+    echo "Failed to upload $UPLOAD_FILE - error code = $retval"
+    exit $retval
 else
     echo "Successfully uploaded $UPLOAD_FILE!"
 fi
